# Generated by Django 5.0.4 on 2024-10-09 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainrobot', '0005_botsettings_buyservice_notf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inovices',
            name='created_date',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
