# Generated by Django 5.0.4 on 2024-10-09 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainrobot', '0006_alter_inovices_created_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inovices',
            name='user_username',
        ),
    ]
