# Generated by Django 5.0.4 on 2024-10-10 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainrobot', '0008_remove_payments_payment_time_payments_created_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptions',
            name='date_created',
        ),
        migrations.AddField(
            model_name='subscriptions',
            name='created_date',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
