# Generated by Django 5.0.4 on 2024-10-14 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainrobot', '0009_remove_subscriptions_date_created_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='pro_id_str',
        ),
        migrations.RemoveField(
            model_name='v2panel',
            name='panel_id_str',
        ),
        migrations.AlterField(
            model_name='products',
            name='panel_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mainrobot.v2panel'),
        ),
    ]
