# Generated by Django 5.0.4 on 2024-10-14 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainrobot', '0010_remove_products_pro_id_str_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inovices',
            name='data_limit',
        ),
        migrations.RemoveField(
            model_name='inovices',
            name='expire_date',
        ),
        migrations.RemoveField(
            model_name='inovices',
            name='panel_name',
        ),
        migrations.RemoveField(
            model_name='inovices',
            name='product_price',
        ),
        migrations.RemoveField(
            model_name='inovices',
            name='product_name',
        ),
        migrations.AddField(
            model_name='inovices',
            name='panel_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mainrobot.v2panel'),
        ),
        migrations.AddField(
            model_name='inovices',
            name='product_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mainrobot.products'),
        ),
    ]
