# Generated by Django 5.0.4 on 2024-10-14 23:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainrobot', '0011_remove_inovices_data_limit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inovices',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mainrobot.users'),
        ),
    ]
