# Generated by Django 5.0.4 on 2024-10-14 23:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainrobot', '0012_alter_inovices_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inovices',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mainrobot.users', to_field='user_id'),
        ),
    ]
