# Generated by Django 5.0.4 on 2024-10-15 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainrobot', '0016_alter_inovices_user_id_alter_payments_user_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payments',
            old_name='product_price',
            new_name='reject_reason',
        ),
        migrations.RenameField(
            model_name='v2panel',
            old_name='panel_sale_mode',
            new_name='sale_mode',
        ),
        migrations.AddField(
            model_name='inovices',
            name='data_limit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inovices',
            name='expire_date',
            field=models.SmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inovices',
            name='panel_name',
            field=models.CharField(default=None, max_length=56),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inovices',
            name='product_name',
            field=models.CharField(default=None, max_length=56),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inovices',
            name='product_price',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='v2panel',
            name='panel_type',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
    ]
