# Generated by Django 5.0.4 on 2024-10-17 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainrobot', '0017_rename_product_price_payments_reject_reason_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='inbounds_selected',
        ),
        migrations.CreateModel(
            name='panelinbounds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inbound_name', models.CharField(blank=True, max_length=64, null=True)),
                ('inbounds_selected', models.TextField(blank=True, default=None, null=True)),
                ('panel_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainrobot.v2panel')),
            ],
            options={
                'db_table': 'v2_inbounds',
            },
        ),
        migrations.AddField(
            model_name='products',
            name='panelinbounds_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainrobot.panelinbounds'),
        ),
    ]
