# Generated by Django 5.0.4 on 2024-10-30 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainrobot', '0018_remove_products_inbounds_selected_panelinbounds_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panelinbounds',
            name='inbounds_selected',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
