# Generated by Django 5.0.4 on 2024-10-30 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainrobot', '0020_alter_panelinbounds_inbounds_selected'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panelinbounds',
            name='inbounds_selected',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
