# Generated by Django 5.0.4 on 2024-11-02 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainrobot', '0021_alter_panelinbounds_inbounds_selected'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='payment_type',
            field=models.CharField(blank=True, max_length=26, null=True),
        ),
    ]
