# Generated by Django 5.0.7 on 2024-11-19 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainrobot', '0022_payments_payment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='inovices',
            name='card_used',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mainrobot.shomarekart'),
        ),
    ]
