# Generated by Django 5.0.7 on 2024-11-19 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainrobot', '0024_alter_shomarekart_bank_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='botsettings',
            name='notif_mode',
            field=models.PositiveSmallIntegerField(default=0, null=True),
        ),
    ]
