# Generated by Django 5.0.4 on 2024-12-06 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainrobot', '0026_botsettings_bot_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='botsettings',
            name='verfiynumber_notf',
            field=models.SmallIntegerField(default=0),
        ),
    ]
