# Generated by Django 5.0.4 on 2024-12-06 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainrobot', '0027_botsettings_verfiynumber_notf'),
    ]

    operations = [
        migrations.RenameField(
            model_name='botsettings',
            old_name='verfiynumber_notf',
            new_name='verifynumber_notf',
        ),
    ]
